### ISSUE TITLE
加载报错

### ISSUE THREAD

**Issue by topsekadmin** [nian-hua/BurpExtender#5]
java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.e1m.<init>(Unknown Source)
	at burp.gzd.a(Unknown Source)
	at burp.fl2.lambda$panelLoaded$0(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

![image](https://user-images.githubusercontent.com/59950798/76500722-06248380-647c-11ea-9086-34f2aff87e12.png)

**Comment by nian-hua** [comment]
是不是你jython的问题？
